import OpenAI from 'openai';

interface DesignAttributes {
  metal: string;
  stone: string;
  setting: string;
  style: string;
  details: string[];
}

export async function analyzeDesignAttributes(
  imageData: string | null,
  textPrompt: string | null
): Promise<DesignAttributes> {
  try {
    const apiKey = import.meta.env.VITE_OPENAI_API_KEY;
    if (!apiKey || apiKey === 'your-openai-api-key-here') {
      throw new Error('OpenAI API key not configured. Please add your API key to the .env file.');
    }

    if (!imageData && !textPrompt) {
      throw new Error('Either image data or text prompt must be provided');
    }

    const openai = new OpenAI({
      apiKey,
      dangerouslyAllowBrowser: true
    });

    const messages = [
      {
        role: "system" as const,
        content: `You are an expert jewelry designer. Analyze the provided image or text and extract key design attributes. Focus on:
1. Metal type and color
2. Stone type and characteristics
3. Setting style and technique
4. Overall design style
5. Notable design details

Return a valid JSON object in this exact format:
{
  "metal": "string",
  "stone": "string",
  "setting": "string",
  "style": "string",
  "details": ["string"]
}`
      }
    ];

    if (imageData) {
      messages.push({
        role: "user" as const,
        content: [
          {
            type: "image_url",
            image_url: {
              url: imageData
            }
          }
        ]
      });
    } else if (textPrompt) {
      messages.push({
        role: "user" as const,
        content: textPrompt
      });
    }

    const completion = await openai.chat.completions.create({
      model: "gpt-4-turbo",
      messages,
      temperature: 0.7,
      max_tokens: 200,
      response_format: { type: "json_object" }
    });

    const response = completion.choices[0].message.content;
    if (!response) {
      throw new Error('No analysis received from AI');
    }

    const parsedResponse = JSON.parse(response);
    
    // Validate response structure
    if (!parsedResponse.metal || !parsedResponse.stone || !parsedResponse.setting || !parsedResponse.style) {
      throw new Error('Invalid response format from AI');
    }

    return parsedResponse;
  } catch (error) {
    console.error('Error analyzing design:', error);
    if (error instanceof Error) {
      throw new Error(`Failed to analyze design: ${error.message}`);
    }
    throw new Error('Failed to analyze design: Unknown error occurred');
  }
}

export async function generateVariationPrompts(
  baseAttributes: DesignAttributes,
  variationCount: number
): Promise<string[]> {
  try {
    const apiKey = import.meta.env.VITE_OPENAI_API_KEY;
    if (!apiKey || apiKey === 'your-openai-api-key-here') {
      throw new Error('OpenAI API key not configured. Please add your API key to the .env file.');
    }

    // Validate input parameters
    if (!baseAttributes.metal || !baseAttributes.stone || !baseAttributes.setting || !baseAttributes.style) {
      throw new Error('Invalid base attributes provided');
    }

    if (variationCount < 1 || variationCount > 10) {
      throw new Error('Variation count must be between 1 and 10');
    }

    const openai = new OpenAI({
      apiKey,
      dangerouslyAllowBrowser: true
    });

    const systemPrompt = `You are an expert jewelry designer. Generate ${variationCount} unique variations of this design while maintaining its core structure:

Base Design:
- Metal: ${baseAttributes.metal}
- Stone: ${baseAttributes.stone}
- Setting: ${baseAttributes.setting}
- Style: ${baseAttributes.style}
- Details: ${baseAttributes.details.join(', ')}

Rules:
1. Keep the fundamental design intact
2. Maintain the same metal and stone type
3. Allow subtle variations in finish and texture
4. Preserve the overall style category
5. Return a valid JSON object with a "variations" array containing the prompts
6. Each prompt should be complete and self-contained

Example response format:
{
  "variations": [
    "A elegant ring with...",
    "A sophisticated pendant with...",
    "A stunning bracelet with..."
  ]
}`;

    const completion = await openai.chat.completions.create({
      model: "gpt-4-turbo",
      messages: [
        {
          role: "system",
          content: systemPrompt
        }
      ],
      temperature: 0.8,
      max_tokens: 1000,
      response_format: { type: "json_object" }
    });

    const response = completion.choices[0].message.content;
    if (!response) {
      throw new Error('No variations generated by AI');
    }

    try {
      const parsedResponse = JSON.parse(response);
      
      if (!parsedResponse.variations || !Array.isArray(parsedResponse.variations)) {
        throw new Error('Invalid response format: missing variations array');
      }

      if (parsedResponse.variations.length !== variationCount) {
        throw new Error(`Expected ${variationCount} variations but received ${parsedResponse.variations.length}`);
      }

      // Validate each variation is a non-empty string
      parsedResponse.variations.forEach((variation: any, index: number) => {
        if (typeof variation !== 'string' || !variation.trim()) {
          throw new Error(`Invalid variation at index ${index}: must be a non-empty string`);
        }
      });

      return parsedResponse.variations;
    } catch (parseError) {
      console.error('Error parsing AI response:', parseError);
      throw new Error('Failed to parse AI response. Please try again.');
    }
  } catch (error) {
    console.error('Error generating variations:', error);
    if (error instanceof Error) {
      throw new Error(`Failed to generate variations: ${error.message}`);
    }
    throw new Error('Failed to generate variations: Unknown error occurred');
  }
}

export function validateVariationPrompts(prompts: string[]): string[] {
  try {
    if (!Array.isArray(prompts)) {
      throw new Error('Prompts must be an array');
    }

    if (prompts.length === 0) {
      throw new Error('No prompts provided');
    }

    return prompts.map((prompt, index) => {
      if (typeof prompt !== 'string') {
        throw new Error(`Invalid prompt at index ${index}: must be a string`);
      }

      if (!prompt.trim()) {
        throw new Error(`Empty prompt at index ${index}`);
      }

      let validatedPrompt = prompt;

      // Ensure proper photography specifications
      if (!validatedPrompt.toLowerCase().includes('professional jewelry photography')) {
        validatedPrompt = `Professional jewelry photography: ${validatedPrompt}`;
      }
      
      // Add standard image requirements if missing
      if (!validatedPrompt.toLowerCase().includes('white background')) {
        validatedPrompt += ', on white background, studio lighting, macro detail';
      }
      
      return validatedPrompt;
    });
  } catch (error) {
    console.error('Error validating prompts:', error);
    if (error instanceof Error) {
      throw new Error(`Prompt validation failed: ${error.message}`);
    }
    throw new Error('Prompt validation failed: Unknown error occurred');
  }
}